"project_identifier" : "youtrack-widgets"
"api_key_env" : CROWDIN_API_KEY
"base_path_env" : CROWDIN_BASE_PATH

"preserve_hierarchy": true

files: [
 {
  "source" : "/src/app/translations/default.pot",
  "dest": "/agile-board-status.pot",
  "translation" : "/src/app/translations/locale_%two_letters_code%.po",
 }
]
